plugins {
    id 'com.android.application'
}

android {
    namespace 'com.dfm.reed'
    compileSdk 36

    defaultConfig {
        applicationId 'com.dfm.reed'
        minSdk 26
        targetSdk 36
        versionCode 8
        versionName '1.1.2'
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
